[build-system]
requires = ["setuptools==83.0.0", "wheel==0.47.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scandoc"
version = "0.1.1"
authors = [
  { name="Thomas Ascioglu", email="thomasascioglu@gmail.com" },
]
maintainers = [
  { name="Thomas Ascioglu", email="thomasascioglu@gmail.com" },
]
description = "Detect and crop documents in an image."
readme = "README.md"
keywords = ["doc", "paper", "document", "scanner", "scan", "image", "crop", "detect"]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "imutils==0.5.4",
    "matplotlib==3.10.8",
    "numpy==2.3.5",
    "opencv-python==4.13.0.92",
    "pillow==12.3.0",
    "scipy==1.17.1",
]

[project.scripts]
scandoc = "scandoc.main_cli:main_cli"

[project.urls]
Homepage = "https://github.com/thomsan/scandoc"
Issues = "https://github.com/thomsan/scandoc/issues"
